---
- name: Forward privileged ports
  become: true
  block:
    - name: Forward port 80
      iptables:
        table: nat
        chain: PREROUTING
        in_interface: '{{ ansible_default_ipv4.interface }}'
        protocol: tcp
        destination_port: '80'
        jump: REDIRECT
        to_ports: '8080'
    - name: Forward port 443
      iptables:
        table: nat
        chain: PREROUTING
        in_interface: '{{ ansible_default_ipv4.interface }}'
        protocol: tcp
        destination_port: '443'
        jump: REDIRECT
        to_ports: '4430'
    - name: Makes rules persistant
      shell: 'iptables-save > /etc/sysconfig/iptables'
      when: ansible_os_family == 'RedHat'
    - name: Make rules persistant
      shell: 'iptables-save > /etc/iptables/rules.v4'
      when: ansible_os_family == 'Debian'
